import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "./utils/providers/ReactQueryProvider";
import "./globals.css";
import { useQueryClient } from '@tanstack/react-query';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = useQueryClient();

  // const profileQuery = useGetQuery<ProfileResponse>("/profile", [
  //   `profile-${'token'}`, token
  // ]);

  React.useEffect(() => {
    const token = localStorage.getItem('authToken');


  }, [queryClient])

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
